server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: area-service
          uri: lb://area-service
          predicates:
            - Path=/area/**
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/categoria/**
        - id: horario-personal-service
          uri: lb://horario-personal-service
          predicates:
            - Path=/horarioPersonal/**
        - id: horario-service
          uri: lb://horario-service
          predicates:
            - Path=/horario/**
        - id: justificativo-personal-service
          uri: lb://justificativo-personal-service
          predicates:
            - Path=/justificativoPersonal/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/pago/**
        - id: personal-service
          uri: lb://personal-service
          predicates:
            - Path=/personal/**
        - id: archivo-service
          uri: lb://archivo-service
          predicates:
            - Path=/archivo/**
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
        - id: autorizacion-personal-service
          uri: lb://autorizacion-personal-service
          predicates:
            - Path=/autorizacionPersonal/**
        - id: calcularPlanilla-service
          uri: lb://calcularPlanilla-service
          predicates:
            - Path=/calcularPlanilla/**
        - id: reportePlanilla-service
          uri: lb://reportePlanilla-service
          predicates:
            - Path=/reporte/**